---
- hosts: localhost 
  user: root
  
  tasks:
    - name: Change the working directory to somedir/ before executing the command
      cmd: chmod 755 local.yml
      args:
        chdir: ansible-code/
        
    - name: Change the working directory to somedir/ before executing the command
      ansible.builtin.shell: sh install-docker.sh >> somelog.txt
      args:
        chdir: ansible-code/
# - name: Copy script from local to remote machine
#    hosts: localhost
#    tasks:
#     - name: Execute script on remote_machine
#       script: sh script.sh  

