- name: Change the working directory to somedir/ before executing the command
    hosts: localhost
    tasks:
      ansible.builtin.shell: install-docker.sh >> somelog.txt
# - name: Copy script from local to remote machine
#    hosts: localhost
#    tasks:
#     - name: Execute script on remote_machine
#       script: sh script.sh  

